on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/denoland/deno:latest
    steps:
      - uses: actions/checkout@v4
      - run: deno ci --prod --skip-types
      - run: deno run build
      - uses: actions/forgejo-release@v2.11.3
        with:
          direction: upload
          release-dir: dist
