on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/denoland/deno:alpine
    steps:
      - run: apk add nodejs npm sed bash jq curl
      - uses: actions/checkout@v6
      - run: deno ci --prod --skip-types
      - run: npm run build
      - uses: actions/forgejo-release@v2
        with:
          direction: upload
          release-dir: dist
