on: [push]
jobs:
  print-content:
    runs-on: docker
    container:
      image: oven/bun:latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list directory contents
        run: bun run build
