on: [push]
jobs:
  build:
    runs-on: docker
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup bun
        uses: https://github.com/oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: build
        run: bun run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
